BibliothecaDAO/loot-survivor

ui/src/app/components/Actions.tsx, ui/src/app/components/Beast.tsx, ui/src/app/components/CreateAdventurer.tsx, ui/src/app/components/TransactionCart.tsx, ui/src/app/components/TxActivity.tsx, ui/src/app/components/Upgrade.tsx, ui/src/app/hooks/useLoadingStore.ts, ui/src/app/page.tsx
This resolves the issue descried by #28.
We are now changing loading state based on adventurer. NOTE: If on the same account, the previous transaction will still need to finish in order for the second transaction to complete loading.
=> add loading by adventurer

ui/src/app/components/Guide.tsx
Items receive a suffix on Greatness 15 and a +3 stat boost as these are random, players need to see what boost is applied given their suffix. 
- Added stat boost type (WIS, INT, DEX, STR, VIT and CHA) by order on G15+ items in game guide.
=> Greatness stat boost updates by order 

contracts/game/src/game/game.cairo, contracts/game/src/tests/test_game.cairo
Light refactor of the obstacle encounter code in the contract
building out integration tests for explore -> obstacle
- Currently it looks like the adventurers starting wand isn't receive XP from the obstacle encounter which it should so that test is failing. Will investigate tomorrow
=> Clean and harden explore -> obstacle contract code

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_meta.cairo, contracts/adventurer/src/bag.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/game/game.cairo, contracts/game/src/game/interfaces.cairo, contracts/game/src/tests/test_game.cairo, contracts/loot/src/loot.cairo, contracts/pack/src/pack.cairo
Better bit packing.
There's a bunch of improvements:
* no use of bitwise builtin, all done via arithmetic
* generic `Packing` trait
* previous implementation was buggy and the bugs were "hidden" because of wrong unit tests
* some packing-unrelated cleanup of imports
The refactor revealed another issue in the game - to pack a `Bag`, we need `12 * 21 = 252` bits, but a `felt252`, despite the name, cannot hold the full value of `252` bits. In other words, a `Bag` with 12 items cannot be packed into a single felt. How to deal with this?
=> refactor: packing

contracts/game/Scarb.toml, contracts/pack/src/pack.cairo
`u256_safe_divmod` libfunc, which is used internally when dividing by u256 which we use when unpacking, is not allowed yet in 0.12. Hence we couldn't build the game with `allowed-libfuncs = true`.
This PR fixes it by using `u512_safe_div_rem_by_u256` libfunc which is allowed.
=> dev: no u256_safe_divmod for now

contracts/game/src/game/messages.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
- assert adventurer is not in battle when buying with test case
- add test to verify adventurer cannot buy item without avail stat upgrade
- qualify expected panics
- tighten gas estimates
=> hardens buy item function

contracts/adventurer/src/adventurer.cairo, contracts/game/src/lib.cairo
- remove return type from functions as they mutate adventurer via ref
- assert item provided is correct type before assigning it to adventurer
- add test cases
=> clean and harden adventurer lib item equipping

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/bag.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/loot/src/loot.cairo, contracts/loot/src/statistics/constants.cairo
- rename to DynamicItem to be more descriptive
- rename get_greatness_level() to get_greatness()
- modify get_greatness() to use self for cleaner client code
=> refactor lootstatistics

contracts/adventurer/src/adventurer.cairo, contracts/game/src/tests/test_game.cairo
Currently if you multi-level and have multiple stat points available, the market will stay fixed after spending a stat.
To fix this, we add adventurers available stat upgrades to the entropy
=> during multi-level, rotate market after each stat upgrade

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/constants/adventurer_constants.cairo, contracts/adventurer/src/exploration.cairo, contracts/adventurer/src/item_meta.cairo, contracts/adventurer/src/item_primitive.cairo, contracts/beasts/src/beast.cairo, contracts/beasts/src/constants.cairo, contracts/combat/src/combat.cairo, contracts/combat/src/constants.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/market/src/market.cairo, contracts/obstacles/src/constants.cairo, contracts/obstacles/src/obstacle.cairo
- item and adventurer level speed reduced by 50%
- use #generate_trait annotation for interface generations
- remove unnecessary imports
- consolidate imports
=> reduce item & advntr leveling speed and general cleanup

contracts/adventurer/src/adventurer.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
- get two hashes from _get_live_entropy (uses game entropy, adventurer entropy, xp, gold, health)
- use first hash for top level explore result: {Beast, Obstacle, Treasure}
- use second has for sub-explore result: {ambushed, treasure type, etc}
=> improves explortation randomness

contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo
- fixes bug where AdventurerState did not include purchased/equipped item
- adds equipped bool and unequipped_item_id to event
- fixes spelling "unequiped" spelling typeo in EquipItem
=> improves PurchasedItem event

contracts/game/src/lib.cairo
- both of these events get consolidated into a generic ItemSpecialUnlocked
- this new event includes item id and item level, along with item specials
=> consolidate and generalizes ItemPrefix and ItemSuffixDiscovered events

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/beasts/src/beast.cairo, contracts/combat/src/combat.cairo, contracts/combat/src/constants.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/loot/src/statistics/item_slot_length.cairo, contracts/market/src/market.cairo
- Renames DisoverHealth to DiscoveredHealth
- Renames DiscoverGold to DiscoveredGold
- Renames DiscoverXP to DiscoveredXP
- Renames DiscoverObstacle to DiscoveredObstacle
- Renames EquipItem to EquippedItem
- Renames GreatnessIncreased to ItemLeveledUp
- Renames AttackBeast to AttackedBeast
- Splits up Beast combat event into AttackedBeast and AttackedByBeast
- DiscoverXP, AttackedBeast, and SlayedBeast will now all be emitted before AdventurerLeveledUp Event
- Fixes bug in which AdventurerLeveledUp event did not include stat upgrade points
- Fixes bug in which PurchasedItem is not being emitted when equip=true
=> significant event refactoring

.github/workflows/build.yml, README.md, contracts/adventurer/Scarb.toml, contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/constants/adventurer_constants.cairo, contracts/game/src/game/constants.cairo, contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/market/src/market.cairo
- Gives adventurer stat upgrade for getting item to G20
- Adds StatUpgradesAvailable event
- Adds StrengthIncreased, DexterityIncreased, VitalityIncreased, IntelligenceIncreased, WisdomIncreased, CharismaIncreased events
- Splits DiscoveredObstacle into DodgedObstacle and HitByObstacle
- Splits FleeAttempt into FleeFailed and FleeSucceeded
- Adds AmbushedByBeast event
- Starter beast will now ambush adventurer for 10HP
- Changes upgrade_stat(stat_id) to upgrade_stat(stat_id, amount) to support efficient multi stat leveling
- Adds util view functions for inspecting market such as: get_weapons_on_market,  get_t1_items_on_market
- Items now receive XP when an obstacle is dodged or damage is taken
- fixes RND bug in which beasts would attack same location for the entirety of a battle
- small …
=> G20 stat bonus, event refactoring, and bug fixes

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_meta.cairo, contracts/adventurer/src/adventurer_stats.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/bag.cairo, contracts/adventurer/src/item_meta.cairo, contracts/adventurer/src/item_primitive.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/loot/src/loot.cairo, contracts/pack/src/pack.cairo
- suffix stat boosts were being applied on pack and unpack
- adventurer lib was preventing stats from boosting over 31
- add overflow protection to stat packing
- add game test for adventurer to level 11
=> fix and harden item suffix stat boost

contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/market/src/market.cairo
- provides external buy_items that takes in adventurer_id and an Array of <item_id, equip>
- includes contract test
=> adds contract support for multi item purchases

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_meta.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/item_meta.cairo, contracts/beasts/src/beast.cairo, contracts/combat/src/combat.cairo, contracts/game/src/game/constants.cairo, contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/obstacles/src/obstacle.cairo
This is a relatively significant change to the game that involves three primary changes:
1. Contract now accepts any combination of 6 starting stats
2. The calculation used to determine if adventurer was able to flee and avoid ambush/obstacles was altered from `(1+relevant_stat) / level` to `relevant_stat/level`. The result is that if the adventurer has no dexterity, they have a 0% chance of fleeing. The contract will not allow adventurers to call flee with 0 dex to prevent this mistake - better for them to battle to the death
3. Simplified beast and obstacle scaling. 
-- The maximum Beast and Obstacle level is now 1 - `2 * adventurer_level`. At level 20 we add 10, making the minimum 11, and maximum 50. At level 30 we add 20, making the minimum 21 and the max 80. At level 40 we add 40 and …
=> Flexible starting stat and difficulty tuning

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/bag.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
- fixes bug where dropped item slots could not be reused
- DroppedItem is now DroppedItems and includes array of item ids dropped
- item_id: u8 changes to item_ids: Array<u8>
- Makes bag lib functions more gas efficient
=> fixes drop bug and changes DroppedItem event

contracts/adventurer/src/adventurer.cairo, contracts/game/src/game/constants.cairo, contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* changes endpoint from buy_items_and_upgrade_stats() to upgrade_adventurer()
* requires all available stat upgrades be used when called
* emits an AdventurerUpgraded event instead of the barrage of individual events: {ItemPurchased, PotionPurchased, [Stat]Increased]}
* AdventuerUpgraded event includes all of the upgrade relevant informationsssssssssssssssssssssssssssssssss
* removes individual operation endpoints: {buy_item, buy_potion, upgrade_stat} as these are inefficient and should not be used
* renames public drop to drop_items to be more descriptive
* updates PurchasedPotion event to include {amount, cost, health_increase}
* fixes bug where buy_items wasn't validated item was available
* Change StatUpgradesAvailable event to UpgradeAvailable
=> Significant changes to adventurer upgrade handling

contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* interface for upgrade_adventurer now takes in stat upgrades explicitly for each stat instead of a Array<u8> of stats
* this allows contract to process any number of stat upgrades with 6 if statements vs loopingssssssssssssssss
* removes buy_items, buy_potions, upgrade_stats, as these are no longer needed
* removes PurchasedItem, PurchasedPotion, [Stat]Increase Events as this information is provided by AdventurerUpgraded
=> improves gas efficiency of upgrade adventurer function

contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
- adds a 'to_the_death' bool to public flee() function
- if set, adventurer will flee until successful or they die
- this implementation is hacky because current version of Cairo is throwing a "Difference in (StatementIdx(46372), Pedersen): Some(22) != Some(0)" with the more elegant recursive solution
- needs integration tests
=> add flee till death option

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_stats.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo
* fixes extra stat boosts being applied
* [regression] events will not include updated stat boosts until next contract call ** this will be addresses in a follow up commit
* provides access to stat boosts separate from adventurer
* significant gas optimizations
=> improves item stat boost management

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/constants/adventurer_constants.cairo, contracts/beasts/src/beast.cairo, contracts/combat/src/combat.cairo, contracts/combat/src/constants.cairo, contracts/game/src/lib.cairo, contracts/obstacles/src/constants.cairo, contracts/obstacles/src/obstacle.cairo
* Abilities are unlocked at Greatness 20
* (T3) Bronze Ring: no special ability (economy option)
* (T2) Silver Ring: bonus +20 luck
* (T1) Gold Ring: 2x gold reward from defeating beasts
* (T1) Platinum Ring: 2x critical hit damage
* (T1) Titanium Ring: 2x special name damage
=> adds unique abilities for Loot Rings

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo, contracts/loot/src/loot.cairo
* Simplifies events emitted when items level up
* Combines ItemLeveledUp and ItemSpecialsUnlocked into a single ItemsLeveledUp
* ItemsLeveledUp provides an array of {item_id, previous_level, new_level, specials}
* Consolidates NewItemsAvailable and UpgradeAvailable events emitted as part of Adventurer level increase and items reaching G20 
** Previously under this scenario, contract would emit several NewItemsAvailable and UpgradeAvailable
=> Item leveling refactor

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_stats.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/bag.cairo, contracts/adventurer/src/exploration.cairo, contracts/adventurer/src/item_meta.cairo, contracts/adventurer/src/item_primitive.cairo, contracts/beasts/src/beast.cairo, contracts/combat/src/combat.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/obstacles/src/obstacle.cairo
* Jewlery items contribute to luck even when in bag
* Provides smaller ability for select Jewlery items prior to g20
* Bronze ring stays the same but gains from being able to contribute luck even when bagged 
** This makes it more reasonable as a starter ring that can still provide after it is upgraded and bagged
* Silver ring stays the same, providing a +20 Luck boost when equipped at G20
* Equipped Gold Ring provides 2x gold reward when defeating beasts and then 4x at g20
* Platinum Ring provides 2x discovery rewards and then 4x at g20 
** This applies to all discovery types {health, gold, xp}
* Titanium Ring provides gold equal to XP when encountering obstacles and then 2x at g20 
** By default, Adventurers do not gain Gold from Obstacles
* G20 Necklace now provides the 2x name bonus …
=> Jewlery ability changes

contracts/game/src/lib.cairo
* Adventurers upgraded VIT multiple times would only receive a single 10HP health potion instead of 30HP
=> fixes only 10hp health for multi VIT increase

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_stats.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/exploration.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* luck is still generated dynamically, not stored
* previously we would calculate luck on-demand
* now we calculate luck when unpacking adventurer and set luck on the Adventurer
* motive for doing this is to have luck included in events via AdventurerState
=> Adds luck to Adventurer struct

contracts/adventurer/src/adventurer.cairo
* adventurer armor was being provided to combat module as the weapon instead of the beast/obstacle
=> fixes beasts and obstacle damage calculation bug

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_meta.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/pack/src/pack.cairo
* Changes public interface `start` to `new_game` to be more description
* Inputs to `new_game` have been greatly simplified, now requiring only: {Client Address, Weapon, Name}
* Removes unused variables {Home Realm, Class} from AdventurerMeta and expands storage space for Name
* Reduces gas for Packing/Unpacking by taking advantage of U256DivRem added in V0.12.1
* Changes external function `drop_items` to `drop`
* Changes external function `upgrade_adventurer` to `upgrade`
* Changes external function `rotate_global_entropy` to `rotate_game_entropy`
* Removes Gold from Beast Seed hash to reduce manipulation
* Adds block timestamp to Adventurer Seed hash to increase randomness
=> Gas optimizations and general code cleanup

contracts/adventurer/src/bag.cairo, contracts/game/Scarb.toml, contracts/game/src/TODO:, contracts/game/src/game/game_entropy.cairo, contracts/game/src/game/interfaces.cairo, contracts/game/src/game/lib.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* previously the entropy and last updated block were stored in two storage slots
* now entropy and last updated block are packed into single storage slot
* this reduces cost of rotating game entropy by ~50% which will be a common call
=> Reduces storage slots for game entropy from 2 to 1

contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* explore, flee, attack, and upgrade will now rotate game entropy if it's available to be rotated
* This will result in an extra storage update for the tx that performs this but this should spread the cost of maintaing game entropy across player base
* external `rotate_game_entropy` is still available
=> rotate game entropy as part of core gameplay

contracts/adventurer/src/adventurer.cairo, contracts/game/src/lib.cairo
* reset actions per block to 0 on block rotation
* use < instead of <= to block player action when it hits the limit vs allowing it to go one over.
* this makes the view functions more intuitive
=> minor adjustment to rate limit

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_meta.cairo, contracts/adventurer/src/adventurer_utils.cairo, contracts/adventurer/src/exploration.cairo, contracts/adventurer/src/item_meta.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo, contracts/market/src/market.cairo
* players must now wait a predetermined number of blocks between starting game and defeating the first starter beast
* AdventurerMetadata has been modified to provide the start_block and the starting_stats. Entropy has been removed.
* StartGame event now includes a `reveal_block` to let clients know what block the player can official start the game
* the commit and reveal specifically protects the adventurer entropy seed and the starting stats from being known in advance
* player will get starting stats assigned after defeating starter beast
* the events emitted from defeating that beast will include the stats
=> adds commit and reveal for stronger entropy

contracts/adventurer/src/adventurer.cairo, contracts/adventurer/src/adventurer_meta.cairo, contracts/adventurer/src/bag.cairo, contracts/game/src/lib.cairo, contracts/loot/src/constants.cairo
* fixes events including outdated stat boosts
* this was most common when items first reached g15
* the impact to the player was client showing wrong stats which is confusin and in the case of charisma, impacts market price calculation
* the two scenarios that would cause this behavior are: ** when items first reach G15
** during equipment changes involving G15 items
=> handle midflight stat boost changes

contracts/game/src/lib.cairo
* dropped item event didn't include stat boosts
* equipped item event was only being emitted for item swapped during battle
=> fixes bug impacting drop and equip item events

contracts/game/src/lib.cairo
* the bug allows players to equip VIT boosting items during upgrade, buy potions, then swap those items without losing that health
* to prevent players from wasting gold, this PR processes item purchases before potion purchases. If player swaps a VIT boosting item as part of their potion, the contract will have the updated VIT and use that to enforce potion limit.
* if a player buys potions up to max health with a VIT boosting item and then swaps out that item after upgrade, contract will lower their health to max health with updated VIT.
=> fixes vitality max health not adjusted during item swaps involving items with VIT boosts 

ui/src/app/components/marketplace/MarketplaceTable.tsx, ui/src/app/components/navigation/TransactionCart.tsx, ui/src/app/components/start/Spawn.tsx, ui/src/app/containers/MarketplaceScreen.tsx, ui/src/app/containers/UpgradeScreen.tsx, ui/src/app/lib/utils/index.ts
We now calculate the VIT that is removed from an item purchase & equip and remove potions if it will take the health below max
=> Add vitality boost removal check

contracts/adventurer/src/adventurer.cairo, contracts/beasts/src/beast.cairo
* previously beasts would not get special names until adventurer reached level 19
* now beasts get level names when they are level 19+, regardless of adventurer level
=> remove advntr lvl from gating beast specials

contracts/adventurer/src/adventurer_meta.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* previously rewards would be distributed to arcade account
* now rewards will be distributed to the primary account
* previously the collectible beasts would be minted to the arcade account
* now collectible beasts will be minted to the primary account
=> use primary account for rewards and beast collectibles

contracts/game/src/game/interfaces.cairo, contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* is_idle(adventurer_id) -> (bool, u16) where the u16 is number of blocks they have been idle
* get_idle_penalty_blocks() -> u64 the current idle penalty threshold in blocks
* these view functions should simplify clients providing a reliable idle penalty block timer for players
=> adds helpful view functions related to idle penalty

contracts/game/src/lib.cairo
* if AA is used for highscore, we'll set owner of Adventurer to PA so for consistency, this event should use owner
* Furthermore, this event could be triggered from slay_idle_adventurer in which caller wouldn't be correct
=> use owner instead of caller for NewHighScore event

contracts/game/src/lib.cairo, contracts/game/src/tests/test_game.cairo
* starting stats and opening market are already locked in when tokens are inserted so this doesn't compromise the integrity of these sensitive elements of the game
=> doubles idle threshold at start of game

ui/src/app/components/start/Spawn.tsx, ui/src/app/containers/BeastScreen.tsx, ui/src/app/containers/InterludeScreen.tsx, ui/src/app/hooks/useUIStore.ts, ui/src/app/lib/utils/index.ts, ui/src/app/page.tsx
- move average block time getter to spawn page
- set the time as a global zustand variable
- only activate if on mainnet
- show the estimate wait time in spawn page
- increase the wait estimate by 1 block
Closes #473 + #457
=> Show estimate wait time on spawn page

contracts/game/src/tests/test_game.cairo, contracts/game_entropy/src/game_entropy.cairo
* triples entropy rotation interval (30mins) and changes idle death penalty to one block less than one third the rotation interval (same as before)
* this reduces opportunities to straddle the entropy rotation within an idle penalty window
=> adjust game entropy rotation interval

indexer/src/items.ts
Previously I changed the naming to store if suffix or prexies unlocked, but the event will emit 0 for the suffix when prefixes are unlocked. Therefore we are overwriting and it displays as null.
Now I am checking in detail whether:
- both a suffix + prefixes were unlockes (store both)
- only prefixes were unlocked (only store these)
- only suffix was unlocked (only store this)
=> fix prefix and suffix naming

ui/src/app/abi/Game.json, ui/src/app/components/leaderboard/LiveRow.tsx, ui/src/app/components/leaderboard/LiveTable.tsx, ui/src/app/components/navigation/TransactionCart.tsx, ui/src/app/containers/LeaderboardScreen.tsx, ui/src/app/lib/utils/syscalls.ts, ui/src/app/page.tsx, ui/src/app/types/index.ts
Implemented the slay Idle adventurers method.
- Fetches all of the `is_idle` results of all adventurers when leaderboard is rendered
- Implements Slay Idle Adventurers button
- Implements slay each of the adventurers in live leaderboard row
=> Slay Idle Adventurers

ui/src/app/lib/burner.ts, ui/src/app/lib/utils/syscalls.ts
Solving some new spawned errors:
`GatewayError: Endpoint is deprecated from version 0.12.3.`
This is as we were calling a particular rpc method through the rpc of the account that had an old config. I have now switched to make these calls through our rpc provider.
=> Fix waitForTransaction gateway errors

contracts/game/src/lib.cairo
* on v1.0.0 the idle counter is reset on every attack
* adventurers can exploit this during certain battles to significantly prolong the duration of the battle which weakens the protection provided by the idle death penalty and global entropy sub-systems
=> only reset idle counter on beast defeat (#552)

contracts/game/src/lib.cairo
* hard codes genesis timestamp to v1.0 contract to preserve reward schedule
=> adjust reward distribution phase for v1.1

contracts/game/src/lib.cairo
* this can be removed after v1.1 optimistic start feature is vetted on Sepolia
=> use 11 block delay on testnet
