BibliothecaDAO/loot-survivor

- indexer/src/indexer/config.py
- ui/src/app/components/Actions.tsx
- ui/src/app/components/BattleDisplay.tsx
- ui/src/app/components/Beast.tsx
- ui/src/app/components/BeastDisplay.tsx
- ui/src/app/components/CreateAdventurer.tsx
- ui/src/app/components/DeathDialog.tsx
- ui/src/app/components/ItemDisplay.tsx
- ui/src/app/components/NotificationDisplay.tsx
- ui/src/app/components/TransactionCart.tsx
- ui/src/app/components/TransactionHistory.tsx
- ui/src/app/components/TxActivity.tsx
- ui/src/app/components/TxStatus.tsx
- ui/src/app/hooks/useLoadingStore.ts
- ui/src/app/lib/utils.ts
- ui/src/app/page.tsx
Improved multicall loaders and notifications for the calls in the array.
Loading ✅
Notifications WIP
Swap Item Death handler WIP
> Update multicall handling

- ui/src/app/components/BattleDisplay.tsx
- ui/src/app/components/Beast.tsx
- ui/src/app/components/BeastDisplay.tsx
- ui/src/app/components/CreateAdventurer.tsx
- ui/src/app/components/DeathDialog.tsx
- ui/src/app/components/DiscoveryDisplay.tsx
- ui/src/app/components/Encounters.tsx
- ui/src/app/components/GameData.tsx
- ui/src/app/components/Leaderboard.tsx
- ui/src/app/components/Marketplace.tsx
- ui/src/app/components/NotificationDisplay.tsx
- ui/src/app/components/TxActivity.tsx
- ui/src/app/hooks/graphql/queries.ts
- ui/src/app/hooks/useLoadingStore.ts
- ui/src/app/hooks/useMusic.tsx
- ui/src/app/hooks/useQueryStore.ts
- ui/src/app/hooks/useUIStore.ts
- ui/src/app/lib/utils.ts
- ui/src/app/page.tsx
Implement full history of Discoveries and Battles in Encounters tab.
Add beast name to discoveries.
Add beast prefixes to beast names.
> Implement Encounters Tab (Discoveries & Battles)

- ui/src/app/components/Adventurer.tsx
- ui/src/app/components/Guide.tsx
- ui/src/app/components/PurchaseHealth.tsx
- add first game guide, will need more updating to reflect upcoming changes
- add ui update to health potion costs to reflect contract change
> game guide 

- ui/src/app/components/ItemDisplay.tsx
- ui/src/app/components/Profile.tsx
- extend width of info component in leaderboard
- fix for pushing stat points off screen for long names
> Fix to issue #103 Show full character info in leaderboard 

- ui/src/app/components/Adventurer.tsx
- ui/src/app/components/AdventurersList.tsx
- ui/src/app/hooks/graphql/queries.ts
Add scroll functionality and increase limit size to show more than 10 adventurers
> Scroll fix to adventurers list

- contracts/adventurer/src/adventurer.cairo
- contracts/beasts/src/beast.cairo
- contracts/game/src/game/game.cairo
- contracts/game/src/tests/test_game.cairo
- contracts/obstacles/src/constants.cairo
- contracts/obstacles/src/obstacle.cairo
Implements: DiscoverGold, DiscoveryXP, DiscoverHealth, FleeAttempt, PurchasedItem, StatUpgraded, PurchasedPotion, EquipItem
> Wire up events

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/item_meta.cairo
- contracts/game/src/game/game.cairo
- contracts/loot/src/loot.cairo
- contracts/loot/src/statistics/constants.cairo
- contracts/obstacles/src/obstacle.cairo
- G15 and G19 name assignments + storage updates
- Emitting Events: {GreatnessIncrease, ItemPrefixDiscovered, ItemSuffixDiscovered}
- Extensive unit test coverage
> Finishes item leveling

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/game/src/game/game.cairo
- contracts/game/src/game/interfaces.cairo
- contracts/game/src/game/messages.cairo
- contracts/game/src/tests/test_game.cairo
- applies stat boosts on adventurer unpack
- removes stat boosts on adventurer pack
- get_adventurer view function provides adventurer with stat boosts
- vitality increases max health
- removing an item with vitality decreases max health
> simplifies stat boosts + adds support for vitality stat

- contracts/market/src/market.cairo
- previous code was only checking if first item in market matched
- test cases now all passing
> fixes bug in market is_item_available

- contracts/game/src/game/messages.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
- add test case for fleeing while not in battle
> hardens test cases for external flee func

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/game/src/tests/test_game.cairo
- remove unncessary adventurer return type from func that mutate adenturer
- provide overflow protection for adding to stats with test cases
- provide underflow protection for deducting stats with test cases
> clean and harden adventurer lib

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/game/src/lib.cairo
- move core logic to adventurer lib with unit test
- make variable names more descriptive
> clean and harden idle adventurer logic

- contracts/adventurer/src/adventurer_meta.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
Order can be derived from home realm
> increase max name size from 4 to 13, remove order

- contracts/game/src/lib.cairo
- adds beast specials to flee event
- adds beast seed to all beast related events
> improves beast events

- contracts/adventurer/src/adventurer.cairo
- contracts/game/src/lib.cairo
- if adventurer discovers health but already has full health, grant or deduct 1 gold to update adventurer state
- adds has_full_health() util function to adventurer with test cases
> hardens against explore loops between game entropy changes

- contracts/adventurer/src/adventurer.cairo
- contracts/game/src/lib.cairo
This resulted in adventurers missing out on stat upgrades when they leveled up via XP discovery
> fixes stat upgrades not allocated on level up from xp discovery

- contracts/adventurer/src/adventurer.cairo
- contracts/beasts/src/beast.cairo
- contracts/game/src/tests/test_game.cairo
- one part of beast name could occassionally be 0
- names generated during encounter differed from battle
> fixes beast name issue

- contracts/game/src/lib.cairo
- adventurer_state, idle_blocks, damage_taken
> adds IdlePenaltyDamage Event

- ui/src/app/components/beast/BattleDisplay.tsx
- ui/src/app/components/navigation/TxActivity.tsx
- ui/src/app/containers/ActionsScreen.tsx
- ui/src/app/containers/BeastScreen.tsx
- ui/src/app/containers/UpgradeScreen.tsx
- ui/src/app/lib/classes.ts
- ui/src/app/page.tsx
> - moved logic for death notis to txActivity

- contracts/adventurer/src/adventurer.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
- After stat upgrade if more stat upgrades are available
- After receiving stat bonus when item reaches G20
> emit NewItemsAvaialble in additional circumstances

- contracts/beasts/src/beast.cairo
- contracts/game/src/lib.cairo
- AmbushedBeast, AttackedBeast, AttackedByBeast, SlayedBeast
> add critical hit bool to beast events

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/bag.cairo
- contracts/adventurer/src/exploration.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
- fixes bug in which AmbushedByBeast was being emitted instead of AttackedByBeast during normal combat
- fixes bug in which items were not receiving xp multplier from obstacles causing inconsistency between obstacle events and item state
- applies stat boosts to upgrade_stat and equip functions to ensure emitted events include adventurer state with stat boosts
- implements code for beast counter attacking after item swap. Note this code is commented out though due to starknet bug
> improves beast combat and event handling

- contracts/game/src/lib.cairo
- adventurer_state in HitByObstacle and DodgedObstacle now includes updated adventurer and item xp
- adventurer_state in SlayedBeast now includes updated item xp
> Improve Combat related events

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/game/src/lib.cairo
- decrease max health increase from 20 to 10 per stat
- grants an immediate +10hp on vitality stat upgrade
> Modifies vitality stat boosts

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/adventurer_utils.cairo
- contracts/game/src/tests/test_game.cairo
- most notably when multiple items of the same type have specials unlocked at the same time
> improve randomness of special names assignments

- contracts/adventurer/src/exploration.cairo
- contracts/beasts/src/beast.cairo
- contracts/beasts/src/constants.cairo
- contracts/combat/src/combat.cairo
- contracts/obstacles/src/constants.cairo
- contracts/obstacles/src/obstacle.cairo
- overflow occurred when getting beast starting health
- added test case to ensure this is properly resolved
- cleaned and hardened auxillery code
> fixes u8 mul overflow in combat lib

- contracts/game/src/game/constants.cairo
- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
- provides external upgrade_stats that takes in adventurer_id and array of stat ids
- includes contract tests
> adds support for multi stat upgrades

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/adventurer_utils.cairo
- contracts/game/src/game/constants.cairo
- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
- contracts/market/src/constants.cairo
- contracts/market/src/market.cairo
* adds buy_items external function
* adds upgrade_stats external function
* adds buy_items_and_upgrade_stats external function
> Adds support for single call upgrade

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* Span was causing frontend issue and difference is meaningless for external funcs
> switch from Span to Array for external functions

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* attack now accepts a 'to_the_death' bool which replaces attack_till_death
* `attack(adventurer_id: u256, to_the_death: bool)`
> consolidate attack and attack_till_death functions

- contracts/adventurer/src/adventurer.cairo
- contracts/beasts/src/beast.cairo
- contracts/combat/src/combat.cairo
- contracts/loot/src/loot.cairo
- contracts/market/src/market.cairo
- contracts/obstacles/src/obstacle.cairo
- this will speed up building and declaring contract
> wrap tests in test mod to reduce sz of artifact

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/bag.cairo
- contracts/adventurer/src/item_meta.cairo
- contracts/adventurer/src/item_primitive.cairo
- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* adds AdventurerUpgraded event with stat increases
* adds EquippedItems that includes equipped and unequipped items
* adds PurchasedItems with array of purchased items + price
* adds PurchasedPotions which includes quantity, cost, and health
* adds mutated flag to Adventurer to make it easier to know when it has been mutated and needs to be updated
* adds mutated flag to Bag to make it easier to know when it has been mutated and needs to be updated
* increases efficiency of game lib
* simplifies contract view functions
> Improves Event System

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* if "till_beast" boolean is set to true in explore(), adventurer will recursively explore until either they die, level up, or find a beast
> adds option to auto explore till beast discovery

- contracts/game/src/game/constants.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* replaces previous idle penalty with death penalty
* there is now only a single tier for idleness and the penalty is death
* changes schema of AdventurerDied event
* IdleDamagePenalty event is now IdleDeathPenalty with diff schema
> idle penalty is now death

- contracts/game/src/lib.cairo
* provides single execution path for recursively exploring till beast is discovered
> simplifies auto exploration

- contracts/obstacles/src/constants.cairo
- contracts/obstacles/src/obstacle.cairo
> extend obstacle set from 15 to 75

- contracts/game/src/lib.cairo
* bug is that items purchased with equip=true were not getting metadata id set
> fixes bug preventing items from reaching g15

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/adventurer/src/exploration.cairo
- contracts/game/src/lib.cairo
* abilities are unlocked at greatness 20
* g20 necklaces doubles value of gold discoveries
* g20 amulets doubles value of health discoveries
* g20 pendents provides bonus stat point (+2 at g20 instead of standard +1)ssssssssssssssssssssssssssssss
> adds unique abilities for Loot necklaces

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/adventurer/src/exploration.cairo
- contracts/loot/src/loot.cairo
- contracts/loot/src/statistics/item_tier.cairo
* Pendent now provides 2x gold discovery instead of Necklace
* Necklace provides a bonus stat upgrade at G20
* Necklace is now a T2 instead of T1
> Minor adjustment to necklace abilities

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* Changes SlayIdleAdventurer(adventurer_id) to SlayIdleAdventurers(Array<adventurer_id>)
> Allow multi slaying of idle adventurers

- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
```rust
struct RewardDistribution {
first_place: PlayerReward,
second_place: PlayerReward,
third_place: PlayerReward,
client: ClientReward,
dao: u256
}
struct PlayerReward {
adventurer_id: u256,
rank: u8,
amount: u256,
address: ContractAddress
}
struct ClientReward {
amount: u256,
address: ContractAddress,
}
```
> Adds RewardDistribution Event

- contracts/beasts/src/constants.cairo
- contracts/obstacles/src/constants.cairo
> lower minimum beast and obstacle damage

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/adventurer_meta.cairo
- contracts/adventurer/src/adventurer_stats.cairo
- contracts/adventurer/src/adventurer_utils.cairo
- contracts/adventurer/src/bag.cairo
- contracts/adventurer/src/item_meta.cairo
- contracts/adventurer/src/item_primitive.cairo
- contracts/combat/src/combat.cairo
- contracts/loot/src/loot.cairo
* tidy up imports
* tidy up comments
> light refactoring

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/adventurer_meta.cairo
- contracts/adventurer/src/leaderboard.cairo
- contracts/adventurer/src/lib.cairo
- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
* adds adventurers gold balance to leaderboard to serve as tie breaker
** tie breaker functionality not implemented as part of this PR
* adds view function for leaderboard
> Reduces storage slots for leaderboard from 6 to 1

- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/lib/burner.tsx
Reverts BibliothecaDAO/loot-survivor#372
> Revert "update provider"

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
* adventurer actions_per_block
* adventurer equipment details
* the global per block rate limit
* various game settings such as: {starting gold, starting health, etc}
> adds helpful view functions

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
* new view function is `get_reveal_block(adventurer_id)`
> fix reveal block in StartGame and add view function

- ui/src/app/components/upgrade/StatAttribute.tsx
- ui/src/app/containers/UpgradeScreen.tsx
- add a getter for nonStatBoosts
- add message for maxing out stats
> Fix contract errors when upgrading stats above 15

- contracts/game/src/lib.cairo
* without this fix, it's possible for adventurer to die from an obstacle but then have an item reach G15 and get a VIT stat boost which will revive them.
> fixes xp applied to items after death from obstacle

- contracts/adventurer/src/adventurer.cairo
* there was a difference between stats being applied in apply_suffix_boost and remove_suffix_boost
> fixes remove suffix boosts bug

- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/components/TopUpDialog.tsx
- ui/src/app/components/intro/ArcadeIntro.tsx
- ui/src/app/lib/burner.ts
- ui/src/app/page.tsx
> Fix eth topups

- contracts/game/src/game/interfaces.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
* includes `can_play(golden_token_id)` view function
> add golden token integration tests

- ui/src/app/components/intro/WalletSelect.tsx
- ui/src/app/hooks/useTransactionCartStore.ts
- ui/src/app/lib/burner.ts
- ui/src/app/lib/connectors.ts
- ui/src/app/lib/constants.ts
- ui/src/app/lib/utils/index.ts
- ui/src/app/lib/utils/syscalls.ts
- ui/src/app/page.tsx
- add lib check for arcade account
- if arcade checkArcadeBalance for topup
- if arcade get and use suggestedMaxFee
- use libs for arcade checks and account getters
> Suggested Max Fee

- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/components/TopUpDialog.tsx
- ui/src/app/components/arcade/TopupInput.tsx
- ui/src/app/hooks/useTransactionCartStore.ts
- ui/src/app/lib/constants.ts
- ui/src/app/lib/utils/index.ts
- ui/src/app/lib/utils/syscalls.ts
- ui/src/app/page.tsx
- fix max topup balance
- topup pops up only for arcades
- topup pops up if suggestedMaxFee > balance
- adds custom eth balance to topup dialog
- removes min balance check
- fixes arcadeIntro
> Arcade topups work

- indexer/src/items.ts
- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/components/arcade/TopupInput.tsx
- ui/src/app/components/intro/ArcadeIntro.tsx
- ui/src/app/lib/burner.ts
- ui/src/app/lib/constants.ts
- fix suffix + prefixes unlocks in indexer
- allow creation of AA without Lords
- fix max games for lords balance
- fix min balance amount
> Allow AA Creation without Lords

- ui/src/app/components/notifications/SpecialBeast.tsx
> Fix tokenId on beast collection url

- indexer/env-goerli
- indexer/env-mainnet
- indexer/src/items.ts
- indexer/src/utils/events.ts
- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/components/navigation/TxActivity.tsx
- ui/src/app/components/notifications/SpecialBeast.tsx
- ui/src/app/lib/burner.ts
- ui/src/app/lib/utils/syscalls.ts
> Slay Idle Adventurers

- indexer/src/utils/events.ts
- ui/src/app/components/navigation/NetworkSwitchError.tsx
- ui/src/app/lib/burner.ts
- ui/src/app/page.tsx
To tighten up security I've added a block on the app until the user switches the connected wallet to the correct network.
> Add page block if wrong network

- ui/package.json
- ui/src/app/components/intro/ArcadeIntro.tsx
- ui/src/app/components/intro/WalletSelect.tsx
- ui/src/app/components/start/CreateAdventurer.tsx
- ui/src/app/components/start/Spawn.tsx
- ui/src/app/containers/AdventurerScreen.tsx
- ui/src/app/lib/arcade.ts
- ui/src/app/lib/connectors.ts
- ui/src/app/page.tsx
- ui/src/app/provider.tsx
- ui/tsconfig.json
- ui/yarn.lock
- add starknetkit
- add argent mobile connector
- update starknet-react
> Integrate starknetkit

- ui/src/app/components/start/Spawn.tsx
- ui/src/app/lib/utils/syscalls.ts
- add call to get current game price in LORDS
- add amount to approval, rather than fixed 25 causing error
> Fix approval contract error from dynamic price

- ui/src/app/components/start/Spawn.tsx
- ui/src/app/lib/utils/syscalls.ts
Error given when trying to play with GT as not passing costToPlay, we are now.
> Fix golden token costToPlay error

- ui/src/app/components/beast/BattleDisplay.tsx
- ui/src/app/components/beast/BeastDisplay.tsx
- ui/src/app/components/notifications/NotificationHandler.tsx
- ui/src/app/lib/utils/syscalls.ts
- fix notification from taking damage from equip
- fix error caused from checking if beast is minted
- fix error from manipulating read only dictionary (equipped items)
> Bug fixes from swapping items

- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/components/arcade/MigrateAA.tsx
- Implement import Arcade Account page on the Arcade Dialog through private key
- Implement button to export private key on the Arcade Account Cards
> Implement AA Migration Tools

- ui/src/app/api/api.ts
- ui/src/app/components/ArcadeDialog.tsx
- ui/src/app/components/arcade/MigrateAA.tsx
- ui/src/app/components/navigation/Header.tsx
- ui/src/app/containers/Onboarding.tsx
- ui/src/app/lib/burner.ts
- ui/src/app/page.tsx
- Implement migration of AA with master account address and private key.
- Add minting lords loader
- Fix minting lords from AA
> Arcade Account Fixes

- contracts/adventurer/src/adventurer.cairo
- contracts/adventurer/src/item_meta.cairo
- contracts/game/src/tests/test_game.cairo
- Includes test case which demonstrates the nature of the bug along with the fix
> fix metadata from dropped items not being reused

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- .gitignore
- README.md
- contracts/game_entropy/src/game_entropy.cairo
- scripts/deploy.sh
- scripts/starkli_setup.sh
* Switch from starknet to starkli
* Adds starkli setup script to automate starkli account creation
* Adds deployment script to simplify game deployment
* Updates readme to account for changes to the contract since it was originally written
* Fixes failing tests in game entropy lib
> Developer Experience Improvements #547

- contracts/adventurer/src/bag.cairo
- contracts/adventurer/src/constants/adventurer_constants.cairo
- contracts/adventurer/src/item_meta.cairo
- contracts/game/src/lib.cairo
- contracts/game/src/tests/test_game.cairo
- contracts/market/src/constants.cairo
* includes test case for reproducing QE bug
* includes test case for reproducing unusable inventory slots
* includes additional test cases for stress testing inventory/metadata
> fixes quantum entanglement bug (metadata duplication)
